services:

  campusmarket-api:

    build: .

    container_name: campusmarket-api

    restart: always

    ports:
      - "8080:8080"
    env_file:
      - .env

  nginx:

    image: nginx:latest

    container_name: campusmarket-nginx

    restart: always

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - campusmarket-api